modLoader="javafml"
loaderVersion="[2,)"

license="MIT"

[[mods]]
modId="debugstickmod"
version="1.0.0"
displayName="Survival Debug Stick"
authors="Reijin"
description='''
Позволяет использовать ванильную палку отладки в режиме выживания
и добавляет для неё крафт (палка + плод хоруса).
'''

[[dependencies.debugstickmod]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.debugstickmod]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
